### ISSUE TITLE
Some Problem

### ISSUE THREAD

**Issue by IamEinstein1** [elect-app/code#1] opened 2020-11-03 07:17 UTC
@TarunKumar29 There is seriously a major problem in this\
I(@IamEinstein1 ) Cloned  the repo and then added some js for the `about page` in `js/about.js`
But it doesnt work
> Can you tell what to do ?

**Comment by TarunKumar29** [comment] 2020-11-03 07:56
Show me the code (Not here) and the problem

**Comment by TarunKumar29** [comment] 2020-11-03 08:11
The issue is closed as there wasn't enough information

**Closed** 2020-11-03 08:11 UTC
Labels: not enough info
